# Generated by Django 4.0.4 on 2022-10-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sikat', models.CharField(max_length=8)),
                ('kodebrng', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('harga', models.BigIntegerField()),
            ],
        ),
    ]
