# Generated by Django 4.0.4 on 2022-10-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barang',
            name='link_gbr',
            field=models.CharField(blank=b'I01\n', max_length=150),
        ),
    ]
