# Generated by Django 4.0.4 on 2022-10-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_barang_link_gbr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barang',
            old_name='sikat',
            new_name='Nama',
        ),
    ]
