# Generated by Django 4.0.4 on 2022-10-25 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rename_sikat_barang_nama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barang',
            name='kodebrng',
        ),
        migrations.AddField(
            model_name='barang',
            name='Kodebrng',
            field=models.CharField(default='BRG', max_length=8),
        ),
        migrations.AddField(
            model_name='barang',
            name='waktu_posting',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='barang',
            name='Nama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='barang',
            name='link_gbr',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
