# Generated by Django 4.0.4 on 2022-11-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_jenis_barang_jenis_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NA', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('jobdesc', models.CharField(max_length=15)),
                ('umur', models.IntegerField()),
                ('jeniskelamin', models.CharField(max_length=10)),
                ('alamat', models.CharField(max_length=50)),
            ],
        ),
    ]
