# Generated by Django 4.0.4 on 2022-11-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_karyawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produk', models.CharField(max_length=10)),
                ('satuan', models.IntegerField()),
                ('jumlah', models.BigIntegerField()),
                ('waktu_order', models.DateTimeField(auto_now_add=True)),
                ('gbr_produk', models.CharField(blank=True, max_length=150)),
            ],
        ),
    ]
